---

- name: "ensure /mnt/nfs exists"
  file:
    path: /mnt/nfs
    state: directory
    mode: '0755' 

- name: Mount nfs
  mount:
    path: /mnt/nfs/docker
    src: chu-nasty.iofq.local:/srv/docker
    fstype: nfs
    opts: auto,rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.6.0.2,local_lock=none,addr=10.6.0.4
    state: present
