---

- name: Set timezone to America/Chicago
  timezone:
    name: America/Chicago

- name: template in resolv.conf
  template:
    src: templates/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644" 

- include_tasks: "install-{{ ansible_distribution }}.yml"
