---

- name: "install epel-release"
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"

- name: "install dnf-automatic"
  yum:
    name: dnf-automatic
    state: present
  when: ansible_distribution == "CentOS"

- name: "template dnf-automatic.conf"
  template:
    src: templates/automatic.conf
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: "0664"
  when: ansible_distribution == "CentOS"

- name: "enable dnf-automatic timer"
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: "install packages..."
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - git
      - dnf-utils
      - nfs-utils
      - sudo
      - openssh-server
  when: ansible_distribution == "CentOS"

- name: "remove packages..."
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - firewalld
  when: ansible_distribution == "CentOS"
